name: "Run on pull requests"

on:
  pull_request:
    types:
      - opened
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: echo "Will add code checks here in next challenge 2"
